name: Python Tests

on: 
  push:
    branches:
      - master
  pull_request:
    types: [opened, assigned]
    branches:
      - master
  workflow_dispatch: 

env:
  ${{ env }}
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup python  
      uses: actions/setup-python@v4
      with:
          python-version: '3.10' 

    - name: Install requirement.txt
      run: |
        python -m pip install --upgrade pip
        pip install -r requirement.txt

    - name: Run pytest
      run: |
        pip install pytest pytest-cov
        pytest ./test_api/test_api_login.py

      
